### ISSUE TITLE
Add GA code

### ISSUE THREAD

**Issue by flo-dot** [poslovnimediji/ps-skoda-mojaskoda-form#1]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-41263367-42"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
 
  gtag('config', 'UA-41263367-42');
</script>

**Comment by hip3r** [comment]
added
